// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"days-gone/app/dao/internal"
)

// userFileDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type userFileDao struct {
	*internal.UserFileDao
}

var (
	// UserFile is globally public accessible object for table user_file operations.
	UserFile = userFileDao{
		internal.NewUserFileDao(),
	}
)

// Fill with you ideas below.
